config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :favorites, only: [:create, :destroy]
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :mutters do
    collection do
      post :confirm
    end
  end
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :mutter
end

app/models/mutter.rb
class Mutter < ApplicationRecord
    validates :content, presence: true
    validates :content, length: { maximum: 140 }

    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites, source: :user
    belongs_to :user, optional: true

    mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }


  before_save { email.downcase! }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  has_many :favorites, dependent: :destroy
  has_many :mutters

  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.contact_mail(@contact).deliver
      redirect_to new_contact_url, notice: 'Contact was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :content)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(mutter_id: params[:mutter_id])
    redirect_to mutters_url, notice: "#{favorite.mutter.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(mutter_id: params[:mutter_id]).destroy
    redirect_to mutters_url, notice: "#{favorite.mutter.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/mutters_controller.rb
class MuttersController < ApplicationController
  before_action :set_mutter, only: [:edit, :update, :destroy, :show]
  before_action :no_log_in, only: [:new, :edit, :show]

  def index
    @mutters = Mutter.all
  end

  def new
    if params[:back]
      @mutter = Mutter.new(mutter_params)
    else
      @mutter = Mutter.new
    end
  end

  def create
    @mutter = Mutter.new(mutter_params)
    @mutter.user_id = current_user.id
    unless params[:cache] == nil
      @mutter.image.retrieve_from_cache! params[:cache][:image]
    end
    if @mutter.save
      ContactMailer.contact_mail(@mutter).deliver
      redirect_to mutters_path, notice: "つぶやきました！"
    else
      render 'new'
    end
  end

  def edit
  end

  def confirm
    @mutter = Mutter.new(mutter_params)
    render :new if @mutter.invalid?
  end

  def destroy
    @mutter.destroy
    redirect_to mutters_path, notice:"削除しました！"
  end

  def update
    if @mutter.update(mutter_params)
      redirect_to mutters_path, notice: "編集しました！"
    else
      render 'edit'
    end
  end

  def show
   @favorite = current_user.favorites.find_by(mutter_id: @mutter.id)
  end

  private
  def mutter_params
    # params[:mutter]
    params.require(:mutter).permit(:content, :id, :image)
  end

  def set_mutter
    @mutter = Mutter.find(params[:id])
  end

  def no_log_in
    if current_user == nil
      redirect_to new_session_path, notice: "ログインして下さい"
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @favorite_mutters = @user.favorites
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to mutters_path, notice: "ユーザー情報を編集しました！"
    else
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/mutters_helper.rb
module MuttersHelper
    def choose_new_or_edit
        if action_name == 'new' || action_name == 'confirm'
          confirm_mutters_path
        elsif action_name == 'edit'
          mutter_path
        end
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :contact_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :contact_email %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :contact_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.content %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Content:</strong>
  <%= @contact.content %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mutter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
            <span class="sr-only">Bootstrap</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Mutter</a>
        </div>
        <div id="gnavi" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'ホーム', "/mutters" %></li>
            <li><%= link_to '新規投稿', "/mutters/new" %></li>
            <% if logged_in? %>
              <li><%= link_to "Profile", user_path(current_user.id) %></li>
              <li><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign up", new_user_path %></li>
              <li><%= link_to "Login", new_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
     </nav>
     </header>
    <!-- <header class="header">
    <nav>
        <ul class="top_menu clearfix">
          <li><%= link_to 'ホーム', "/mutters" %></li>
          <li><%= link_to '新規投稿', "/mutters/new" %></li>
        </ul>
      </nav>
    </header> -->
    <!-- 以下、コメントが二重に出てたから削除 -->
    <!-- <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %> -->
    <!-- 以上 -->
    <%= yield %>
    <footer class="footer">
    <p>yusuke miyazaki</p>
    </footer>

  </body>
</html>

app/views/mutters/_form.html.erb
<header class="header">
    <nav>
        <ul class="top_menu clearfix">
          <li><a href="/mutters">ホーム</a></li>
          <li><a href="/mutters/new">新規投稿</a></li>
        </ul>
      </nav>
</header>

<article class="content">

<%= form_with(model: @mutter, local: true ,url: choose_new_or_edit) do |form| %>
  <% if @mutter.errors.any? %>
    <div id="error_explanation">
      <h2><%= @mutter.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @mutter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="mutter_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

<%= link_to "つぶやき一覧へもどる", mutters_path %>

<footer class="footer">
  <p>yusuke miyazaki</p>
</footer>

app/views/mutters/confirm.html.erb
<article class="content">

<h3>確認ページ</h3>

<%= form_with(model: @mutter, url: mutters_path, local: true) do |form| %>
  <%= form.hidden_field :content %>

  <p>content:<%= @mutter.content %></p>

  <% if @mutter.image.present? %>
  <p>image:</p>
  <%= image_tag(@mutter.image.url) %>
  <%= hidden_field_tag :"cache[image]", @mutter.image.cache_name %>
  <% end %>
  <br>
  <%= form.submit  "登録" %>
<% end %>

<%= form_with(model: @mutter, url: new_mutter_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :content %>
  <%= form.submit "もどる",name: 'back' %>
<% end %>

app/views/mutters/edit.html.erb
<article class="content">

<h2>編集する</h2>
<br>
<%= form_with(model: @mutter, local: true ,url: choose_new_or_edit) do |form| %>
  <% if @mutter.errors.any? %>
    <div id="error_explanation">
      <h2><%= @mutter.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @mutter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="mutter_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <br>
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :mutter_image %>
    <%= form.hidden_field :image_cache %>
  </div>
  <br>
  <%= form.submit %>
<% end %>
<br>
<%= link_to "つぶやき一覧へもどる", mutters_path %>

app/views/mutters/index.html.erb
<article class="content">

<!-- <h1>つぶやきアプリ</h1> -->

<%= image_tag 'photo.jpg', :size =>'700x150'%>

<h2 class="container">つぶやきアプリ<span class="label label-default">new!!</span></h2>
<br>
      <ul class="bg-success row">
          <li class="col-sm-6 col-md-3">ルール① 毎日つぶやく</li>
          <li class="col-sm-6 col-md-3">ルール② ポジティブなことをつぶやく</li>
          <li class="col-sm-6 col-md-3">ルール③ 毎日見返す</li>
          <li class="col-sm-6 col-md-3">ルール④ 過去の自分を超える！</li>
      </ul>

<br>
<p><%= notice %></p>
<br>
<table class="table">
  <tr>
    <th>過去つぶやき一覧</th></th>
  </tr>

<% @mutters.each do |mutter| %>
  <tr>
    <td><%= mutter.content %></td>
    <td><%= image_tag(mutter.image_url) if mutter.image.present? %></td>
    <td class="btn btn-success"><%= link_to "詳細", mutter_path(mutter.id) %></td>
    <% unless current_user == nil %>
      <% if current_user.id == mutter.user_id %>
        <td class="btn btn-warning"><%= link_to "編集", edit_mutter_path(mutter.id) %></td>
        <td class="btn btn-danger"><%= link_to '削除', mutter_path(mutter.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
      <% end %>
    <% end %>
  </tr>
<% end %>
</table>
<br>
<%= link_to '新しくつぶやく', new_mutter_path %>

</article>

app/views/mutters/new.html.erb
<article class="content">
<br>
<h2>つぶやく</h2>

<%= form_with(model: @mutter, local: true ,url: choose_new_or_edit) do |form| %>
  <% if @mutter.errors.any? %>
    <div id="error_explanation">
      <h2><%= @mutter.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @mutter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mutter_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <br>
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :mutter_image %>
    <%= form.hidden_field :image_cache %>
  </div>
  <br>

  <%= form.submit %>
<% end %>
<br>
<%= link_to "つぶやき一覧へもどる", mutters_path %>

app/views/mutters/show.html.erb
<h1>詳細画面</h1>
<p>内容: <%= @mutter.content %></p>
<p>
  <strong>Image:</strong>
  <%= image_tag(@mutter.image_url) if @mutter.image.present? %>
</p>

<% unless @mutter.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(mutter_id: @mutter.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(mutter_id: @mutter.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<h1>ユーザ情報の編集</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.label :image %>
  <%= f.file_field :image, id: :user_image %>
  <%= f.hidden_field :image_cache %>
  </div>

  <%= f.submit "更新" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.label :image %>
  <%= f.file_field :image, id: :user_image %>
  <%= f.hidden_field :image_cache %>
  </div>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>

<p>
  <strong>ユーザー画像:</strong>
  <%= image_tag @user.image_url if @user.image.present? %>
</p>

<%= link_to "ユーザー情報を編集する", edit_user_path(@user.id) %>
<br>
<h1>お気に入りつぶやき一覧</h1>

<% @favorite_mutters.each do |a| %>
<%= a.mutter.content %>
<% end %>